### Installing Memcached ###

- name: install and configure components
  shell:
    sudo apt install -y memcached python3-memcache

- name: edit memcached configuration file
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/memcached.conf
    regexp: "-1 127.0.0.1"
    line: "-1 10.0.0.11"

# Finalize installation

- name: restart memcached service
  shell:
    service memcached restart

